Be less noisy shutting HttpServers in failure conditions.
If we attempt to shut down the HttpServers too soon after starting
them up, we may get Connection Refused exceptions because they have
not completed their startup procedure.  PJ noticed this and put in
a TODO to investigate, and customers noticed it in the logs.
Unlike PJ's observation, this exception was thrown out of connect():

com.google.enterprise.adaptor.Application issueSleepGetRequest
WARNING: Error performing shutdown GET
java.net.ConnectException: Connection refused
  at java.net.PlainSocketImpl.socketConnect(Native Method)
  [chomp...]
  at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:850)
  at com.google.enterprise.adaptor.Application.issueSleepGetRequest(Application.java:280)
  at com.google.enterprise.adaptor.Application.httpServerShutdown(Application.java:244)
  at com.google.enterprise.adaptor.Application.daemonDestroy(Application.java:230)
  at com.google.enterprise.adaptor.Application.stop(Application.java:177)

This change ignores the ConnectExceptions, rather than logging them.

Code Review: http://codereview.appspot.com/253680043